### ISSUE TITLE
inputType "List" doesn't work correctly in Contao 5.4.*

### ISSUE THREAD

**Issue by LIVID-Media** [madeyourday/contao-rocksolid-custom-elements#178]
Contao 5.4.*
PHP 8.3

By editing an element with inputType "list" changes can be saved only once. After saving the page doesn't respond to the "Save" button nor by hitting Enter in an input field. If you change the order of the elements or add new ones, the appearance of the TinyMCE changes. Perhaps this bug is also related to the new Turbo function!?

**Comment by ausi** [comment]
This should be fixed in version 2.4.12, please verify if this works in your setup too.

**Comment by LIVID-Media** [comment]
Unfortunately, the error still exists with 2.4.12 under Contao 5.4.14. As there are no error messages in the console, I can't say what the problem might be. However, the error no longer occurs under Contao 5.5!

Only some HTML elements are duplicated when saving, but this also happens several times under Contao 5.5 and should therefore not be a problem:

![Image](https://github.com/user-attachments/assets/85d6cfd0-b5b2-4fac-abe9-a53b527723c6)

After saving:

![Image](https://github.com/user-attachments/assets/27b4bf1c-6363-479a-8dd6-def0b088b977)

**Comment by ausi** [comment]
> However, the error no longer occurs under Contao 5.5!

That should be sufficient then as version 5.4 reachted its EOL just now.
